### ISSUE TITLE
Add support for GraniteDS Remoting

### ISSUE THREAD

**Issue by sharp-bits** [sharp-bits/jmeter-amf#1]

**Comment by mordechai** [comment]
Does this mean graniteds is supported?

**Comment by sharp-bits** [comment]
Based on one report that it was working. If you try it out and it doesn't work, please re-open this ticket with the details.

**Comment by mordechai** [comment]
So silly question here but where would granite_config.xml go?

**Comment by hemau23** [comment]
my web application is one granite ds and i have update your source code acordingly and its working fine with me from last 6 month. hemau23@gmail.com
