### ISSUE TITLE
Corrected Build Instructions

### ISSUE THREAD

**Issue by mslinn** [sharp-bits/jmeter-amf#11]
1. Download JMeter and JMeter-AMF Plugin
2. Extract JMeter to a directory (let's call it JMETER_HOME)
3. Extract JMeter-AMF Plugin to a directory (for me it was steeltomato-jmeter-amf-52ba0fd - let's call it JAMF_HOME)
4. Build the Plugin as follows:
   - Create the directories $JAMF_HOME/lib, $JAMF_HOME/lib/api and $JAMF_HOME/lib/ext
   - From BlazeDS 4.x, copy blazeds-common.jar and blazeds-core.jar to $JMETER_HOME/lib/ext
   - Edit $JAMF_HOME/build.properties and change the value of install.dir to the expanded value of $JMETER_HOME/lib. Add two more lines to override the values of lib.dir and lib.api. For me the file became:

``````
release.version=1.1
install.dir=E:/work/wC/dependencies/jakarta-jmeter-2.5/lib/ext
lib.dir=E:/work/wC/dependencies/jakarta-jmeter-2.5/lib
lib.api=E:/work/wC/dependencies/jakarta-jmeter-2.5/lib/ext```
   * Run ant install. This creates JMeter-AMF.jar and copies it to $JMETER_HOME/lib/ext/
``````

**Comment by sharp-bits** [comment]
Thanks for this. I had not really considered the build process for someone who had not set up the complete dev environment. Since JMeter always comes packaged with the necessary libs, it might be easier to just always declare JMETER_HOME instead of install.dir and build the rest of the path properties off it.

**Comment by sharp-bits** [comment]
Updated build process so that only jmeter.home needs to be defined. Also provided a new task to automatically download the BlazeDS libs from Spring's maven repo.
