### ISSUE TITLE
AMFProxy SSL issue

### ISSUE THREAD

**Issue by achints** [sharp-bits/jmeter-amf#12]
The following code causes an SSL connection even if my application is non-ssl, but is running on non-default port (e.g. my staging server).

Issue is that if the staging url (non-SSL) is http://xyz.abc.com:8180, AMFProxy treats it as an SSL request due to the below parsing, which is incorrect.  My non-ssl is running on port 8180, but since AMF Proxy treats it as SSL, application does not work.  Please address the below to account for non-standard (non 80) ports to not be treated as SSL if protocol is http.

<AMFProxy code>
// With ssl request, url is host:port (without https:// or path)
                String[] param = request.getUrl().split(":");  // $NON-NLS-1$
                if (param.length == 2) {
                    log.debug("Start to negotiate SSL connection, host: " + param[0]);
                    clientSocket = startSSL(clientSocket, param[0]);
                } else {
                    log.warn("In SSL request, unable to find host and port in CONNECT request");
                }
                // Re-parse (now it's the http request over SSL)
                request.parse(new BufferedInputStream(clientSocket.getInputStream()));
</AMFProxy code>

**Comment by sharp-bits** [comment]
The code provided is in an if block that will only run if the HTTP request method is "CONNECT" 

`if (request.getMethod().startsWith(HTTPConstants.CONNECT))`

So, there are a few things that might be going on here. If you do not have any [URL filtering](http://jakarta.apache.org/jmeter/usermanual/component_reference.html#HTTP_Proxy_Server) enabled, it is very possible that the proxy is just picking up other random traffic from your machine. If that isn't the case, you might want to try a traffic monitor program like [Charles](http://www.charlesproxy.com/) to see exactly what is going on and ensure that there are not HTTPS connection being made in your application.

You did not mention whether sampling process is successful or not. Does the result of the SSL sample contain anything? If so, what parts are different than your expectation?

**Comment by achints** [comment]
You are right, it is picking up other traffic not related to my app.  Thanks for the very prompt response!  I shall close this issue now.
