### ISSUE TITLE
AMF request fails

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [sharp-bits/jmeter-amf#13]
Hello,

I have tried setting up jmeter as explained in the user guide.
However, when running my application through the AMF proxy server I get this error:

Error: Send failed

Details: Channel.Connect.Failed error NetConnection.Call.Failed: HTTP: Status 400: url: 'http://192.168.10.21:8081/epa/messagebroker/amf'

the request data logged in jmeter is the following (what I find strange is the Host: 192.168.10.21:8081:8081):

 http://192.168.10.21:8081/epa/messagebroker/amf

[no cookies]

Request Headers:
Cache-Control: no-cache
Accept: _/_
Accept-Encoding: gzip, deflate
Connection: keep-alive
content-type: application/x-amf
Accept-Language: nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4
Accept: _/_
Origin: http://192.168.10.21:8081
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.835.187 Safari/535.1
Accept-Encoding: gzip,deflate,sdch
Referer: http://192.168.10.21:8081/epa/Main.swf
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
Host: 192.168.10.21:8081:8081
Content-Length: 21

It would be super if I'd be able to load test my application making use of jmeter.
Thanks a lot already for open sourcing your library!

Kind regards,

Lander Beeuwsaert

**Comment by sharp-bits** [comment]
I think the duplicated port is just a display bug, I also see it when using non-standard ports.

I am assuming you pulled this output from the Request tab of a View Results Tree that was attached to the AMF Proxy node. If that is the case, I am curious what is in the Response Data tab (really request data in this case). Could you provide text and AMF versions of this output? It seems unlikely that 21 bytes could provide a valid AMF message.

Regardless of that, the proxy shouldn't care whether the data is valid or not. It should just stream it along anyway. Do you have any problem using other traffic monitors (e.g. [Charles](http://www.charlesproxy.com/))? If not, could you provide the header and data output from Charles?

**Comment by LanderBeeuwsaert** [comment]
It is indeed the output of the request tab. The response data tab remains empty.
I do not have this problem with charles, the content length there is also larger.

What I see in charles is a first request: amf (5).
Then when I login to my application, I see two requests, with two responses.
The first request (auth.8) returns a faultString: There was an unhandled failure on the server. flex/messaging/security/TomcatLoginHolder.
The second however shows that the login service has been called successfully.

Any ideas?
If you want, I can send over the charles session file.

**Comment by sharp-bits** [comment]
Not really sure what is going on. If you don't mind, please send the session to my e-mail.

Is it the first request (amf (5)) that fails with the proxy and causes your client to give the error? If not, which ones succeed and fail?

If you leave the browser proxy off until you have authenticated, can you then turn it on and sample successfully?

**Comment by sharp-bits** [comment]
Please try recording with the normal HTTP proxy in both HTTP Client 3.1 and HTTP Client 4 sampler modes. Let me know if the client still gives the 400 error message using either of these samplers.

**Comment by sharp-bits** [comment]
To correct a previous error, the proxy is actually converting all requests to XML then back to AMF before delivering to the server. It looks like an alias I entered for command messages was causing the problem. The fix will be included in 1.2.

Thanks for all your help in tracking this one down, it was pretty elusive.

**Comment by LanderBeeuwsaert** [comment]
Cool, thanks!
